# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - chaimoto
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - wonfix
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"
