name: Suspendisse pulvinar
description: Praesent congue erat
labels: [bug]
body:
  - type: input
    attributes:
      label: URL Praesent congue erat
      description: >-
        Donec pede justo fringilla [Praesent congue erat](https://russianfedora.github.io/FAQ/).
  - type: textarea
    attributes:
      label: Donec pede justo fringilla
      description: >-
        Cras risus ipsum
    validations:
      required: true
