name: Nunc interdum lacus
description: Phasellus magna. Nunc egestas, augue at pellentesque laoreet, felis eros vehicula leo, at malesuada velit leo quis pede.
labels: [bug]
body:
  - type: input
    attributes:
      label: URL Fusce neque
      description: >-
        Fusce neque [Fusce neque FAQ](https://russianfedora.github.io/FAQ/).
  - type: textarea
    attributes:
      label: Pellentesque habitant
      description: >-
        Phasellus gravida semper nisi. Praesent blandit laoreet nibh. Quisque malesuada placerat nisl.
    validations:
      required: true
