on:
  workflow_dispatch:

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Generate GitHub App access token"
        uses: tibdex/github-app-token@v1
        id: get_app_token
        with:
         app_id: 80505
         private_key: ${{ secrets.PJAPP_PRIVATE_KEY }}

      - name: "Push changes"
        env:
          GITHUB_TOKEN: ${{ steps.get_app_token.outputs.token }}
        run: |
          git config --get http.${{ github.server_url }}/.extraheader && git config --unset-all http.${{ github.server_url }}/.extraheader
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config credential.${{ github.server_url }}.helper '!f() { test "$1" = get && echo "password=$GITHUB_TOKEN"; }; f'
          git config credential.${{ github.server_url }}.username x-access-token
          touch $( date '+%Y-%m-%d_%H-%M-%S' )
          git add .
          git commit -m "Testing githubapp $(date)"
          git push origin ${{ github.ref }} --force-with-lease --tags
