on:
  pull_request:
    types:
      - opened
jobs:
  based:
    runs-on: ubuntu-latest
    steps:
      - name: Get base branch
        env:
          PR_BASE: ${{ github.head_ref }}
        run: echo "The head of this PR is $PR_BASE"
